#!/bin/sh

# This is the example configuration file for river(1).
#
# If you wish to edit this, you will probably want to copy it to
# $XDG_CONFIG_HOME/river/init or $HOME/.config/river/init first.
#
# See the riverctl(1) man page for complete documentation

# Variables
mod="Mod4"
term="alacritty"
menu="wofi --show drun"
locker="swaylock_river"

# Apps
riverctl spawn "kile"
riverctl spawn 'waybar'
riverctl spawn 'mako'
riverctl spawn '/usr/lib/xdg-desktop-portal -r'
riverctl spawn '/usr/lib/xdg-desktop-portal-wlr'

# Background
riverctl spawn 'swaybg -i "$HOME/Imágenes/Wallpapers/dracula_arch.png" -m fill'

# Mod + Return to spawn the terminal
riverctl map normal $mod+Shift Return spawn $term

# Run application laucher
riverctl map normal $mod+Shift Space spawn $menu

# Mod+W to close the focused view
riverctl map normal $mod W close

#TODO: Add kill command

# Mod+J and Mod+K to focus the next/previous view in the layout stack
riverctl map normal $mod J focus-view next
riverctl map normal $mod K focus-view previous

# Mod+Shift+J and Mod+Shift+K to swap the focused view with the next/previous
# view in the layout stack
riverctl map normal $mod+Shift J swap next
riverctl map normal $mod+Shift K swap previous

# Mod+Return to bump the focused view to the top of the layout stack
riverctl map normal $mod Return zoom

# Mod+H and Mod+L to decrease/increase the main factor by 5%
# If using rivertile(1) this determines the width of the main stack.
riverctl map normal $mod H mod-layout-value kile fixed main_factor -0.05
riverctl map normal $mod L mod-layout-value kile fixed main_factor +0.05

# Mod+Shift+H and Mod+Shift+L to increment/decrement the number of
# main views in the layout
riverctl map normal $mod+Control H mod-layout-value kile fixed main_amount 1
riverctl map normal $mod+Control L mod-layout-value kile fixed main_amount -1

# Mod+Alt+{H,J,K,L} to move views
riverctl map normal $mod+Mod1 H move left 100
riverctl map normal $mod+Mod1 J move down 100
riverctl map normal $mod+Mod1 K move up 100
riverctl map normal $mod+Mod1 L move right 100

# Mod+Alt+Control+{H,J,K,L} to snap views to screen edges
riverctl map normal $mod+Mod1+Control H snap left
riverctl map normal $mod+Mod1+Control J snap down
riverctl map normal $mod+Mod1+Control K snap up
riverctl map normal $mod+Mod1+Control L snap right

# Mod+Alt+Shif+{H,J,K,L} to resize views
riverctl map normal $mod+Mod1+Shift H resize horizontal -100
riverctl map normal $mod+Mod1+Shift J resize vertical 100
riverctl map normal $mod+Mod1+Shift K resize vertical -100
riverctl map normal $mod+Mod1+Shift L resize horizontal 100

# Mod + Left Mouse Button to move views
riverctl map-pointer normal $mod BTN_LEFT move-view

# Mod + Right Mouse Button to resize views
riverctl map-pointer normal $mod BTN_RIGHT resize-view

for i in $(seq 1 9); do
	tags=$((1 << ($i - 1)))

	# Mod+[1-9] to focus tag [0-8]
	riverctl map normal $mod $i set-focused-tags $tags

	# Mod+Shift+[1-9] to tag focused view with tag [0-8]
	riverctl map normal $mod+Shift $i set-view-tags $tags

	# Mod+Ctrl+[1-9] to toggle focus of tag [0-8]
	riverctl map normal $mod+Control $i toggle-focused-tags $tags

	# Mod+Shift+Ctrl+[1-9] to toggle tag [0-8] of focused view
	riverctl map normal $mod+Shift+Control $i toggle-view-tags $tags
done

# Mod+0 to focus all tags
# Mod+Shift+0 to tag focused view with all tags
all_tags=$(((1 << 32) - 1))
riverctl map normal $mod 0 set-focused-tags $all_tags
riverctl map normal $mod+Shift 0 set-view-tags $all_tags

# Mod+Space to toggle float
riverctl map normal $mod Space toggle-float

# Mod+F to toggle fullscreen
riverctl map normal $mod F toggle-fullscreen

# Custom layouts
riverctl map normal $mod D set-layout-value kile string focused "{v: h h}"
riverctl map normal $mod+Shift D set-layout-value kile string focused "{h: v h}"
riverctl map normal $mod+Shift T set-layout-value kile string focused "{t}"

# Declare a passthrough mode. This mode has only a single mapping to return to
# normal mode. This makes it useful for testing a nested wayland compositor
riverctl declare-mode passthrough

# Mod+F11 to enter passthrough mode
riverctl map normal $mod F11 enter-mode passthrough

# Mod+F11 to return to normal mode
riverctl map passthrough $mod F11 enter-mode normal

# Powermenu
riverctl declare-mode powermenu
riverctl map normal $mod Pause enter-mode powermenu
riverctl map powermenu None l spawn "$locker && riverctl enter-mode normal"
riverctl map powermenu None e exit
riverctl map powermenu None s spawn '$locker && systemctl suspend && riverctl enter-mode normal'
riverctl map powermenu None r spawn 'systemctl reboot'
riverctl map powermenu Shift S spawn 'systemctl poweroff'
riverctl map powermenu $mod Pause enter-mode normal
riverctl map powermenu $mod Escape enter-mode normal

# Set repeat rate
riverctl set-repeat 50 300

# Set the layout on startup
riverctl layout rivertile left

# Set app-ids of views which should float
riverctl float-filter-add "float"
riverctl float-filter-add "popup"

# Set app-ids of views which should use client side decorations
riverctl csd-filter-add "gedit"

# Set opacity and fade effect
riverctl opacity 1.0 0.75 0.0 0.1 20

riverctl default-layout kile

# Gaps

riverctl set-layout-value kile int view_padding 10

# Borders

riverctl border-color-focused '#bd93f9'
riverctl border-color-unfocused '#282a36'

# Screnshots

riverctl map normal None Print spawn 'grimshot copy area'
riverctl map normal Shift Print spawn 'grimshot save area'


# Idle

riverctl spawn 'swayidle -w timeout 600 "systemctl suspend"'

#GTK

gsettings set org.gnome.desktop.interface gtk-theme "Dracula"
