[theme]
name = "modern"
[theme.overrides]
idle_bg = "#3B4252"
idle_fg = "#D8DEE9"
# alternating_tint_bg = "#B48EAD"
# alternating_tint_fg = "#D8DEE9"
critical_bg = "#BF616A"
critical_fg = "#D8DEE9"
good_bg = "#A3BE8C"
good_fg = "#D8DEE9"
info_bg = "#EBCB8B"
info_fg = "#2E3440"
# separator_bg = "#2E3440"
# separator_fg = "#ECEFF4"
# separator
warning_bg = "#D08770"
warning_fg = "#D8DEE9"

[icons]
name = "awesome"

[[block]]
block = "focused_window"
max_width = 35
show_marks = "visible"

[[block]]
block = "pacman"
interval = 600
format = "{pacman} + {aur} = {both} updates available"
format_singular = "{both} update available"
format_up_to_date = "system up to date"
warning_updates_regex = "(linux|linux-lts|linux-zen)"
aur_command = "paru -Qua"

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{mem_total_used_percents}"
format_swap = "{swap_used_percents}"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "load"
interval = 1
format = "{1m}"

[[block]]
block = "sound"

[[block]]
block = "time"
interval = 60
format = "%a %d/%m %R"
locale = "es_MX"
