#!/bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
pgrep -x lxsession > /dev/null || lxsession &
pgrep -x xidlehook > /dev/null || xidlehook_suspend &

$HOME/.config/polybar/launch.sh
$HOME/.fehbg &
killall picom ; picom -bc --experimental-backend &
~/scripts/remaps &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          15

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Brave-browser desktop='^2'
bspc rule -a Screenkey manage=off
bspc rule -a Zathura state=tiled
bspc rule -a Pavucontrol state=floating follow=on
bspc rule -a Qalculate-gtk state=floating follow=on

bspc config normal_border_color "#5E81AC"
bspc config active_border_color "#88C0D0"

bspc config focused_border_color "#81A1C1"

bspc config presel_feedback_color "#5E81AC"
